/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Simulat extends javax.swing.JFrame {
    public CPU myCPU;
    public Memory myMemory;
    public Bus myBus;
    static Simulat panel;
    /**
     * Creates new form SimMain
     */
    public Simulat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_R0 = new javax.swing.JLabel();
        textT0 = new javax.swing.JTextField();
        label_R1 = new javax.swing.JLabel();
        label_R2 = new javax.swing.JLabel();
        label_R3 = new javax.swing.JLabel();
        textT1 = new javax.swing.JTextField();
        textT2 = new javax.swing.JTextField();
        textT3 = new javax.swing.JTextField();
        label_X1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label_X3 = new javax.swing.JLabel();
        textX1 = new javax.swing.JTextField();
        textX2 = new javax.swing.JTextField();
        textX3 = new javax.swing.JTextField();
        label_PC = new javax.swing.JLabel();
        text_PC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textAddress = new javax.swing.JTextField();
        textValue = new javax.swing.JTextField();
        setR0 = new javax.swing.JButton();
        setR1 = new javax.swing.JButton();
        SingleStep = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConsolePad = new javax.swing.JTextArea();
        setR2 = new javax.swing.JButton();
        setR3 = new javax.swing.JButton();
        setX1 = new javax.swing.JButton();
        setX2 = new javax.swing.JButton();
        setX3 = new javax.swing.JButton();
        setPC = new javax.swing.JButton();
        setMemory = new javax.swing.JButton();
        SingleScript = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_R0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_R0.setText("R0");
        label_R0.setToolTipText("");

        textT0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textT0ActionPerformed(evt);
            }
        });

        label_R1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_R1.setText("R1");

        label_R2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_R2.setText("R2");

        label_R3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_R3.setText("R3");
        label_R3.setFocusTraversalPolicyProvider(true);

        textT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textT1ActionPerformed(evt);
            }
        });

        textT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textT2ActionPerformed(evt);
            }
        });

        label_X1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_X1.setText("X1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("X2");

        label_X3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_X3.setText("X3");

        textX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textX1ActionPerformed(evt);
            }
        });

        label_PC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_PC.setText("PC");

        text_PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_PCActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Memory");

        textAddress.setText("Address");
        textAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddressActionPerformed(evt);
            }
        });

        textValue.setText("Value");
        textValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textValueActionPerformed(evt);
            }
        });

        setR0.setText("Set");
        setR0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setR0ActionPerformed(evt);
            }
        });

        setR1.setText("Set");
        setR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setR1ActionPerformed(evt);
            }
        });

        SingleStep.setText("SingleStep");
        SingleStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleStepActionPerformed(evt);
            }
        });

        ConsolePad.setColumns(20);
        ConsolePad.setRows(5);
        jScrollPane1.setViewportView(ConsolePad);

        setR2.setText("Set");
        setR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setR2ActionPerformed(evt);
            }
        });

        setR3.setText("Set");
        setR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setR3ActionPerformed(evt);
            }
        });

        setX1.setText("Set");
        setX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setX1ActionPerformed(evt);
            }
        });

        setX2.setText("Set");
        setX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setX2ActionPerformed(evt);
            }
        });

        setX3.setText("Set");
        setX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setX3ActionPerformed(evt);
            }
        });

        setPC.setText("Set");
        setPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPCActionPerformed(evt);
            }
        });

        setMemory.setText("Set");
        setMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMemoryActionPerformed(evt);
            }
        });

        SingleScript.setText("SingleScript");
        SingleScript.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textValue, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_R3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textT3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_R2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textT2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label_R1)
                                    .addComponent(label_R0, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textT0, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textT1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setR0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setR1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setR2)
                            .addComponent(setR3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_X1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textX1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setX1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textX2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setX2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_X3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textX3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setX3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_PC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_PC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setPC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(SingleScript, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SingleStep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textT0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_R0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(setX1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_X1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textX1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(setR0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_R1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textT1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textX2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setR1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setX2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label_R2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textT2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_X3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textX3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setX3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_PC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_R3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textT3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_PC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(setR3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(setPC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(setR2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addComponent(SingleStep, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SingleScript, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setR0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setR0ActionPerformed
        short Data=  Short.parseShort(textT0.getText()) ; 
        panel.myCPU.R[0].write(Data);        // TODO add your handling code here:
    }//GEN-LAST:event_setR0ActionPerformed

    private void textT0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textT0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textT0ActionPerformed

    private void textT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textT1ActionPerformed

    private void setR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setR1ActionPerformed
         short Data=  Short.parseShort(textT1.getText()) ; 
        panel.myCPU.R[1].write(Data);        // TODO add your handling code here:
    }//GEN-LAST:event_setR1ActionPerformed

    private void textT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textT2ActionPerformed

    private void setR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setR2ActionPerformed
       short Data=  Short.parseShort(textT2.getText()) ; 
        panel.myCPU.R[2].write(Data); 
    }//GEN-LAST:event_setR2ActionPerformed

    private void setR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setR3ActionPerformed
       short Data=  Short.parseShort(textT3.getText()) ; 
        panel.myCPU.R[3].write(Data);         // TODO add your handling code here:
    }//GEN-LAST:event_setR3ActionPerformed

    private void SingleStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleStepActionPerformed
      Instruction Inst=new Instruction(SingleScript.getText(),panel.myCPU);
      Inst.ParseInst();
      myCPU.IR.write(Inst.Inst);
       //Test Only.. Merely debug
   //   System.out.println("debug current Inst at single step "+Inst.Inst);
     //       System.out.println("debug current PC at single step "+myCPU.PC.get());
      panel.myCPU.writeMemory(myCPU.PC.get(), Inst.Inst, 0, 0);
    
      myCPU.OperatingSystem.run(); //For now. Just Run it for single time.  Alert: Should be completed if all templates are checked.
        

// ConsolePad.get  // TODO add your handling code here:
    }//GEN-LAST:event_SingleStepActionPerformed

    private void setX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setX1ActionPerformed
             short Data=  Short.parseShort(textX1.getText()) ; 
        panel.myCPU.X[1].write(Data);    // TODO add your handling code here:
    }//GEN-LAST:event_setX1ActionPerformed

    private void textX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textX1ActionPerformed

    private void setX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setX2ActionPerformed
              short Data=  Short.parseShort(textX2.getText()) ; 
        panel.myCPU.X[2].write(Data);    
    }//GEN-LAST:event_setX2ActionPerformed

    private void setX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setX3ActionPerformed
                short Data=  Short.parseShort(textX3.getText()) ; 
        panel.myCPU.X[3].write(Data);    // TODO add your handling code here:
    }//GEN-LAST:event_setX3ActionPerformed

    private void setPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPCActionPerformed
       short Data=  Short.parseShort(text_PC.getText()) ;  // TODO add your handling code here:
       panel.myCPU.PC.set(Data);
    }//GEN-LAST:event_setPCActionPerformed

    private void text_PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_PCActionPerformed

    private void textAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddressActionPerformed

    private void textValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textValueActionPerformed

    private void setMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMemoryActionPerformed
      short Data1=  Short.parseShort(textAddress.getText()) ;   
        short Data2= Short.parseShort(textValue.getText());// TODO add your handling code here:
        panel.myCPU.writeMemory(Data1,Data2,0,0);
        System.out.println("debug set mem in panel: Data1:"+Data1+" Data2:"+Data2);
    }//GEN-LAST:event_setMemoryActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            	   panel=new Simulat();
                        panel.setVisible(true);
                        panel.myBus=new Bus();
                        panel.myCPU=new CPU(panel.myBus);
                        panel.myMemory=new Memory(panel.myBus);
                        panel.myBus.Init(panel.myCPU,panel.myMemory);
                
            }
        });
    }

    // Variables declaration - do not modify                                                    
    public javax.swing.JTextArea ConsolePad;
    public javax.swing.JTextField SingleScript;
    public javax.swing.JButton SingleStep;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel label_PC;
    public javax.swing.JLabel label_R0;
    public javax.swing.JLabel label_R1;
    public javax.swing.JLabel label_R2;
    public javax.swing.JLabel label_R3;
    public javax.swing.JLabel label_X1;
    public javax.swing.JLabel label_X3;
    public javax.swing.JButton setMemory;
    public javax.swing.JButton setPC;
    public javax.swing.JButton setR0;
    public javax.swing.JButton setR1;
    public javax.swing.JButton setR2;
    public javax.swing.JButton setR3;
    public javax.swing.JButton setX1;
    public javax.swing.JButton setX2;
    public javax.swing.JButton setX3;
    public javax.swing.JTextField textAddress;
    public javax.swing.JTextField textT0;
    public javax.swing.JTextField textT1;
    public javax.swing.JTextField textT2;
    public javax.swing.JTextField textT3;
    public javax.swing.JTextField textValue;
    public javax.swing.JTextField textX1;
    public javax.swing.JTextField textX2;
    public javax.swing.JTextField textX3;
    public javax.swing.JTextField text_PC;
    // End of variables declaration                   
}
